apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: percona-server-mongodb-provider
rules:
- apiGroups: ["core.openeverest.io"]
  resources: ["providers", "instances"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["core.openeverest.io"]
  resources: ["instances/status"]
  verbs: ["get", "update", "patch"]
- apiGroups: ["psmdb.percona.com"]
  resources: ["perconaservermongodbs", "perconaservermongodbbackups", "perconaservermongodbrestores"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods", "services", "secrets"]
  verbs: ["get", "list", "watch"]