- apiGroups:
    - ""
  resources:
    - configmaps
    - persistentvolumeclaims
    - secrets
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - patch
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances
  verbs:
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.openeverest.io
  resources:
    - instances/finalizers
  verbs:
    - update
- apiGroups:
    - core.openeverest.io
  resources:
    - instances/status
  verbs:
    - get
    - patch
    - update
- apiGroups:
    - core.openeverest.io
  resources:
    - providers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - psmdb.percona.com
  resources:
    - perconaservermongodbbackups
    - perconaservermongodbrestores
    - perconaservermongodbs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - psmdb.percona.com
  resources:
    - perconaservermongodbbackups/status
    - perconaservermongodbrestores/status
    - perconaservermongodbs/status
  verbs:
    - get
- apiGroups:
    - psmdb.percona.com
  resources:
    - perconaservermongodbs/finalizers
  verbs:
    - update
